import { Inter } from "next/font/google"
import { getLocale } from "next-intl/server"
import NavBar from "@/components/NavBar"

import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({ children }) {
  const locale = await getLocale()

  return (
    <html lang={locale}>

      <body className={inter.className}>


        <NavBar />{children}
      </body>
    </html>
  )
}

